# Generated by Django 4.0.6 on 2022-07-26 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_product_price_product_status_productattribute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name_plural': '5.Products Attribute'},
        ),
    ]
