# Generated by Django 4.0.6 on 2022-08-01 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_productattribute_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banner',
            new_name='Banners',
        ),
    ]
