# Generated by Django 4.0.6 on 2022-08-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_productattribute_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='alt_txt',
            field=models.CharField(max_length=10),
        ),
    ]
