# Generated by Django 4.0.6 on 2022-08-02 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_size_alt_txt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
