# Generated by Django 4.0.6 on 2022-08-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_product_options_alter_productattribute_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='image',
            field=models.ImageField(upload_to='banner_img/'),
        ),
    ]
