# Generated by Django 4.0.6 on 2022-08-02 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_banners_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banners',
            old_name='image',
            new_name='img',
        ),
    ]
