# Generated by Django 4.0.6 on 2022-08-02 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_image_banners_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banners',
            old_name='img',
            new_name='image',
        ),
    ]
