# Generated by Django 4.0.6 on 2022-08-03 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_img_banners_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='spec',
            new_name='latin',
        ),
    ]
