# Generated by Django 4.0.6 on 2022-08-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_spec_product_latin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='describe',
            field=models.TextField(),
        ),
    ]
