# Generated by Django 4.0.6 on 2022-08-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_product_describe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='latin',
            new_name='spec',
        ),
    ]
