# Generated by Django 4.1 on 2022-08-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_product_nutrition_alter_product_store_instru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nutrition',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='store_instru',
            field=models.TextField(),
        ),
    ]
