# Generated by Django 3.2 on 2022-08-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20220818_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='order_status',
            field=models.CharField(choices=[('process', 'In Process'), ('process', 'Shipped'), ('process', 'Delivered')], default='process', max_length=50),
        ),
    ]
