# Generated by Django 3.2 on 2022-08-18 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20220818_0917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddressbook',
            options={'verbose_name_plural': '7.Address Book'},
        ),
    ]
