# Generated by Django 3.2 on 2022-08-18 03:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_useraddressbook_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddressbook',
            name='address',
        ),
        migrations.AddField(
            model_name='useraddressbook',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddressbook',
            name='street',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
